stages: # Ici on déclare toutes nos étapes
  - build
  - deploy

job:build:
  stage: build 
  script:
    - sudo docker-compose down
    - mkdir ./database/data && chown -R gitlab-runner ./database && chmod 775 -R ./database
    - sudo docker-compose build
  only:
    - master

job:deploy:
  stage: deploy 
  script: 
    - sudo docker-compose up -d
  only:
    - master
