stages: # Ici on déclare toutes nos étapes
  - build
  - deploy

job:build:
  stage: build 
  script: sudo docker-compose build

job:test:
  stage: deploy 
  script: sudo docker-compose up -d

only:
  - master
