stages: # Ici on déclare toutes nos étapes
  - build
  - deploy

job:build:
  stage: build 
  script:
    - sudo docker-compose down
    - mkdir -p ./database/data
    - sudo docker-compose build
  only:
    - master

job:deploy:
  stage: deploy 
  script: 
    - sudo docker-compose up -d
    - sudo chgrp -hR gitlab-runner ./database && sudo chmod 770 -R ./database
  only:
    - master
