version: '3'

services:
  database:
    image: postgres:9.6.20
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - gesco-database:/var/lib/postgresql/data

  php-fpm:
    build:
      context: "."
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://admin:admin@database:5432/db?serverVersion=5.7
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    ports:
      - 8000:8000

volumes:
  gesco-database: