version: "3"

services:
  database:
    image: postgres:9.6.20-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - /gesco/php/database/data:/var/lib/postgresql/data

  php-fpm:
    build:
      context: "."
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://admin:admin@database:5432/db?serverVersion=5.7
      - POSTGRES_PASSWORD=admin
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - KEYCLOAK_CLIENT=gesco
      - KEYCLOAK_SECRET=2b25a6d4-5c2e-4111-aa27-20556a8f458b
      - KEYCLOAK_URL=http://matthieu.ga:2099/auth/realms/imt-mines-ales/protocol/openid-connect/userinfo
    ports:
      - "8000:8000"
