version: '3'

services:
  database:
    build:
      context: ./database
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql/data

  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://admin:admin@database:5432/db?serverVersion=5.7
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ../backend:/var/www
    ports:
      - "8000:8000"
